baseURL = 'http://zedsoft.hu'
languageCode = 'en-us'
title = 'ZedSoft Blog'
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 4
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "ZedSoft Blog"
    weight = 1
    contentDir = "content/en"

[params]
  text_color = ""
  author = "Zoltan V"
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  recent_posts_number = 2